
export interface GitHubFile {
  path: string;
  content: string;
}

export const deployToGitHub = async (
  token: string,
  repoName: string,
  files: GitHubFile[]
): Promise<string> => {
  const headers = {
    Authorization: `token ${token}`,
    Accept: 'application/vnd.github.v3+json',
    'Content-Type': 'application/json',
  };

  // 1. Get User Details
  const userRes = await fetch('https://api.github.com/user', { headers });
  if (!userRes.ok) throw new Error('Invalid GitHub Token');
  const user = await userRes.json();
  const username = user.login;

  // 2. Create Repository
  const createRepoRes = await fetch('https://api.github.com/user/repos', {
    method: 'POST',
    headers,
    body: JSON.stringify({
      name: repoName,
      description: 'Business website generated by Kakani Build',
      auto_init: true,
      private: false,
    }),
  });

  if (!createRepoRes.ok) {
    const err = await createRepoRes.json();
    if (err.message !== 'Repository creation failed.') {
       throw new Error(err.message || 'Failed to create repository');
    }
  }

  // 3. Upload Files
  for (const file of files) {
    const filePath = `https://api.github.com/repos/${username}/${repoName}/contents/${file.path}`;
    
    await fetch(filePath, {
      method: 'PUT',
      headers,
      body: JSON.stringify({
        message: `Deploy ${file.path} via Kakani Build`,
        content: btoa(file.content),
      }),
    });
  }

  // 4. Enable GitHub Pages
  await fetch(`https://api.github.com/repos/${username}/${repoName}/pages`, {
    method: 'POST',
    headers,
    body: JSON.stringify({
      source: {
        branch: 'main',
        path: '/',
      },
    }),
  });

  return `https://${username}.github.io/${repoName}/`;
};
